version: 0.2

env:
  secrets-manager:
     username: arn:aws:secretsmanager:us-east-1:156380389105:secret:kavitha4-fY4t3h:user1
     password: arn:aws:secretsmanager:us-east-1:156380389105:secret:kavitha4-fY4t3h:user2
phases:
  runtime-versions:
    nodejs: 10
  commands:
    - wget https://www.python.org/ftp/python/3.8.5/python-3.8.5.exe
    - install python-3.8.5.exe
    - sudo pip install boto3
    - wget https://releases.hashicorp.com/terraform/0.10.4/terraform_0.10.4_linux_amd64.zip
    - unzip terraform_0.10.4_linux_amd64.zip
    - sudo mv terraform /bin
    - rm terraform_0.10.4_linux_amd64.zip
    - apt-get update
    - terraform init 
    - terraform apply
  build:
    commands:
      - echo "$username"
      - echo "$password" 
