version: 0.2

env:
  secrets-manager:
     username: arn:aws:secretsmanager:us-east-1:736097574176:secret:kavitha4-Lutky8:user1
     password: arn:aws:secretsmanager:us-east-1:736097574176:secret:kavitha4-Lutky8:user2
phases:
  install:
    commands:
      - wget https://www.python.org/ftp/python/3.8.6/python-3.8.6.exe
      - echo installing python 3.8.6
      - apt-get update
      - apt install python-3.8.6
      - sudo pip install boto3
      - wget https://releases.hashicorp.com/terraform/0.10.4/terraform_0.10.4_linux_amd64.zip
      - unzip terraform_0.10.4_linux_amd64.zip
      - sudo mv terraform /bin
      - rm terraform_0.10.4_linux_amd64.zip
      - apt-get update
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - terraform init 
      - terraform apply
      - echo "$username"
      - echo "$password" 
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
